version: '3.8'

services:
   oracle-price-server:
     image: public.ecr.aws/classic-terra/oracle-price-server
     platform: linux/amd64
     build: 
      context: price-server
      dockerfile: Dockerfile
      labels:
        - "Contains everything needed to run the Oracle price server"
   oracle-feeder:
     image: public.ecr.aws/classic-terra/oracle-feeder
     platform: linux/amd64
     build: 
       context: feeder
       dockerfile: Dockerfile
       labels:
        - "Contains everything needed to run the Oracle 'feeder' (voting) dapp"